# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Layers of Learning
tagline:             'Understanding How Machines Learn'
description:         'A Machine Learning and Data Science Blog created and maintained by Daniel Vieira.'
url:                 #http://lanyon.getpoole.com
baseurl:             'blog'
paginate:            5

# About/contact
author:
  name:              Daniel Vieira
  url:               #https://twitter.com/mdo
  email:             kovauviske@poli.ufrj.br

# Custom vars
version:             1.0.0
